### ISSUE TITLE
cannot update to 3.4.0. on api.

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-errorhandler#34]
composer require dotkernel/dot-errorhandler 3.4.0
./composer.json has been updated
Running composer update dotkernel/dot-errorhandler
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires dotkernel/dot-errorhandler 3.4.0 -> satisfiable by dotkernel/dot-errorhandler[3.4.0].
    - dotkernel/dot-errorhandler 3.4.0 requires psr/http-message ^2.0 -> found psr/http-message[2.0] but the package is fixed to 1.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by bidi47** [comment]
resolved in https://github.com/dotkernel/dot-errorhandler/pull/35
also removed php 8.1 because it failed checks

**Comment by arhimede** [comment]
still cannot upgrade on api 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires dotkernel/dot-errorhandler 3.4.0 -> satisfiable by dotkernel/dot-errorhandler[3.4.0].
    - dotkernel/dot-errorhandler 3.4.0 requires psr/http-message ^2.0 -> found psr/http-message[2.0] but the package is fixed to 1.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by bidi47** [comment]
the most recent release for dotkernel/dot-errorhandler is 3.4.0 which doesn't have the recent composer updates
is it ok to release 3.4.1?
